//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testflow.MasterCore.Resources.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n_engineCore_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n_engineCore_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testflow.MasterCore.Resources.locale.i18n_engineCore_en", typeof(i18n_engineCore_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send message when messenger is deactivated.
        /// </summary>
        internal static string CannotSendWhenDeactive {
            get {
                return ResourceManager.GetString("CannotSendWhenDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event enqueue operation time out..
        /// </summary>
        internal static string EventEnqueueTimeOut {
            get {
                return ResourceManager.GetString("EventEnqueueTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event queue is overflow..
        /// </summary>
        internal static string EventQueueOverflow {
            get {
                return ResourceManager.GetString("EventQueueOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect delegate type &quot;{0}&quot;..
        /// </summary>
        internal static string IncorrectDelegate {
            get {
                return ResourceManager.GetString("IncorrectDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of event parameter should be &quot;{0}&quot;..
        /// </summary>
        internal static string IncorrectParamType {
            get {
                return ResourceManager.GetString("IncorrectParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation panle class &lt;{0}&gt; should have a constructor with string type parameter..
        /// </summary>
        internal static string InvalidOIConstructor {
            get {
                return ResourceManager.GetString("InvalidOIConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid runtime information name: {0}..
        /// </summary>
        internal static string InvalidRuntimeInfoName {
            get {
                return ResourceManager.GetString("InvalidRuntimeInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid runtime object type: {0}..
        /// </summary>
        internal static string InvalidRuntimeObjType {
            get {
                return ResourceManager.GetString("InvalidRuntimeObjType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OI class &lt;{0}&gt; does not contain a event named as &lt;{1}&gt;..
        /// </summary>
        internal static string OIClassEventNotExist {
            get {
                return ResourceManager.GetString("OIClassEventNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OI class &lt;{0}&gt; does not contain a method named as &lt;{1}&gt;..
        /// </summary>
        internal static string OIClassMethodNotExist {
            get {
                return ResourceManager.GetString("OIClassMethodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation class &lt;{0}&gt; cannot be found..
        /// </summary>
        internal static string OIClassNotFound {
            get {
                return ResourceManager.GetString("OIClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation panel error:{0}.
        /// </summary>
        internal static string OperationPanelError {
            get {
                return ResourceManager.GetString("OperationPanelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation timeout..
        /// </summary>
        internal static string OperatoinTimeout {
            get {
                return ResourceManager.GetString("OperatoinTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global variable named as &lt;{0}&gt; does not exist..
        /// </summary>
        internal static string ParamVariableNotExist {
            get {
                return ResourceManager.GetString("ParamVariableNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test generation timeout..
        /// </summary>
        internal static string TestGenTimeout {
            get {
                return ResourceManager.GetString("TestGenTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence execution timeout..
        /// </summary>
        internal static string TestRunTimeout {
            get {
                return ResourceManager.GetString("TestRunTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceGroup with input arguments cannot run with out test project..
        /// </summary>
        internal static string UnexistArgumentSource {
            get {
                return ResourceManager.GetString("UnexistArgumentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexist session event &quot;{0}&quot;..
        /// </summary>
        internal static string UnexistEvent {
            get {
                return ResourceManager.GetString("UnexistEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session with id &quot;{0}&quot; dose not exist..
        /// </summary>
        internal static string UnexistSession {
            get {
                return ResourceManager.GetString("UnexistSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered message type: {0}..
        /// </summary>
        internal static string UnregisteredMessage {
            get {
                return ResourceManager.GetString("UnregisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operating system cannot support platform &lt;{0}&gt;..
        /// </summary>
        internal static string UnsupportedPlatform {
            get {
                return ResourceManager.GetString("UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test aborted by user operation..
        /// </summary>
        internal static string UserAbort {
            get {
                return ResourceManager.GetString("UserAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Error: {0}..
        /// </summary>
        internal static string UserAbortError {
            get {
                return ResourceManager.GetString("UserAbortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled the execution of sequence..
        /// </summary>
        internal static string UserCancel {
            get {
                return ResourceManager.GetString("UserCancel", resourceCulture);
            }
        }
    }
}
